### ISSUE TITLE
Add Polyfill for TextDecoderStream to Ensure Compatibility with Bun

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [ax-llm/ax#21]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

[TextDecoderStream](https://github.com/oven-sh/bun/issues/5648) is currently not supported in Bun. I propose adding a polyfill for TextDecoderStream to ensure compatibility without requiring an additional import statement. This will enhance the usability of the project and prevent potential issues for users running their code in environments where TextDecoderStream is not natively supported.

Example:

```
import { TextDecoderStream as NativeTextDecoderStream } from 'stream/web';
import { TextDecoderStream as PolyfillTextDecoderStream } from './path/to/text-encoding-polyfill';

// Check if TextDecoderStream is available, if not use the polyfill
const TextDecoderStream = typeof NativeTextDecoderStream !== 'undefined' ? NativeTextDecoderStream : PolyfillTextDecoderStream;

export { TextDecoderStream }
```

**Comment by dosco** [comment]
i'll take a look.

**Comment by dosco** [comment]
fixed let me know if it works for you

**Comment by TYRONEMICHAEL** [comment]
Awesome. Will pull in the latest version and test a little later tonight.

**Comment by TYRONEMICHAEL** [comment]
Nice. Confirm it is working.
