### ISSUE TITLE
Calling agents that have functions

### ISSUE THREAD

**Issue by beddows** [ax-llm/ax#65]
- **I'm submitting a ...**
  [?] bug report
  [?] question about how to use this project

- **Summary**
Hi @dosco ,
This pattern isn't working for me:
```typescript
const ai = new AxAI({name, apiKey});
ai.setOptions({ debug: true });

const agent1 = new AxAgent(ai, { name, description, signature, functions });
const agent2 = new AxAgent(ai, { name, description, signature, functions });

const agent = new AxAgent(ai, { name, description, signature, agents[agent1, agent2] });
``` 

It works if agent1 & agent2 don't have functions (like in the [agent](https://github.com/ax-llm/ax/blob/main/src/examples/agent.ts) example). But if they do, they don't work. Either it's a bug or I'm misunderstanding something fundamental to agents.

As for signatures, I'm using something like:
```typescript
signature1: agent1Request -> result "the result"
signature2: agent2Request -> result "the result"

signature: request -> result
``` 
Agent names and descriptions are detailed, distinct, and include proper parameters with the required property in their functions. Their functions return an empty result, since they're not called.

It works if I put all the functions in the main agent, but I'd rather use a modular approach to scale the function calling. This is with Anthropic.

**Comment by dosco** [comment]
can you try the latest release and confirm there were some fixes.

**Comment by beddows** [comment]
Thanks, I think that was the problem, it must have been stuck on a previous version.
